[runtime]
    server = "eddydoor"
    port = 8899

[private]
    secret = "oauth.xmwuyi.com"

[resource]
    # todo: 版本
[resource.mysql]
    dsn = "root:123456@tcp(localhost:3308)/eddydoor"

[resource.redis]
    addr = "localhost:6379"